# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f252044c2685d1a27e623d9ee2633d8a273e298b953a1bc8cadb4492db5e3ed0d15457d0a8423e26d0788f6dced043923110ed4cefa30f6a54b64dd95ddd6f7d

test:
  secret_key_base: 24760e4772fb867543ad6bd360557a45d5cc15b16fa47e14a5578d3f6dcb6e78e236d1d0b2532057b09ac9e447ebee469d4d268cca33760945544b0293d5e3a1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
